export const platos = [
  {
    id: 1,
    imagen: require("../imgs/chicharronDePollo.jpeg"),
    titulo: "Chicharrón de Pollo",
    desc: "Con Salsa agridulce, Arroz, Soya Picante, Barbacoa o seco",
    precio: 40,
  },
  {
    id: 2,
    imagen: require("../imgs/Pollo_Rebosado.jpg"),
   titulo: "Pollo Rebosado ",
    desc: "Con Salsa agridulce, Brócoli",
    precio: 40,
  },
  {
    id: 3,
    imagen: require("../imgs/Pollo_Cortado.jpg"),
    titulo: "Pollo Cortado",
    desc: "Con verduras, Arroz",
    precio: 40,
  },
  {
    id: 4,
    imagen: require("../imgs/Camaron_Rebosado.jpg"),
    titulo: "Camarón Rebosado",
    desc: "Con Salsa agridulce, Salsa Picante ",
    precio: 50,
  },
  {
    id: 5,
    imagen: require("../imgs/Pollo_Asado.jpg"),
    titulo: "Pollo Asado",
    desc: "Al estilo Pekín",
    precio: 40,
  },
  {
    id: 6,
    imagen: require("../imgs/Carne_Cortada.jpg"),
    titulo: "Carne Cortada ",
    desc: "Carne Cortada ",
    precio: 40,
  },
  {
    id: 7,
    imagen: require("../imgs/Cerdo_Rebosado.jpg"),
    titulo: "Cerdo Rebosado",
    desc: "Con Salsa agridulce, Pimentón ",
    precio: 40,
  },
  {
    id: 8,
    imagen: require("../imgs/Chuleta_de_Cerdo.jpg"),
    titulo: "Chuleta de Cerdo",
    desc: "Con Salsa agridulce, Soya, Picante, Barbacoa o Seco",
    precio: 40,
  },
  {
    id: 9,
    imagen: require("../imgs/pescadoFrito.jpeg"),
    titulo: "Pescado Frito",
    desc: "Con Salsa agridulce, Soya Picante, Barbacioa o seco",
    precio: 40,
  },
  {
    id: 10,
    imagen: require("../imgs/Tofu_Frito.jpg"),
    titulo: "Tofu Frito",
    desc: "Con verduras",
    precio: 33,
  },
];
